#!/bin/sh
delay=5
log() {
    printf >&2 'autorestart [%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)" "$*"
}
while true; do
    log "running: $*"
    "$@"
    log "exited $?"
    log "sleep ${delay}"
    sleep "${delay}"
done
